//! Baked trust-anchor public keys — the staged generation point (R-5/FIX-24).
//!
//! This file is the SINGLE pinned module (`baked_keys`) holding the public-key
//! trust anchor compiled into `nmbl-init`. It is committed EMPTY: the default
//! dev build links a zero-length [`BAKED_KEYS`] and [`REQUIRE_KEYS`] = `false`,
//! so a feature-free / measure-only build is byte-identical to the pre-feature
//! binary (modulo the one cold crane rebuild for the added file — FIX-63).
//!
//! When the operator configures `boot.nmbl.signing.publicKeys`, the Nix builder
//! (`mkNmblInit { publicKeys }`) REGENERATES this file: it emits one
//! `include_bytes!("baked_key_N.bin")` entry per key, paired with its [`AlgId`],
//! and flips [`REQUIRE_KEYS`] to `true`. The per-key `.bin` blobs are
//! fileset-unioned into the crane source (the terminfo/font precedent), because
//! `cleanCargoSource` drops `include_bytes!` blobs.
//!
//! ## Why two consts
//!
//! - [`BAKED_KEYS`] is the trust material: each `(raw-pubkey-bytes, alg)` pair
//!   is parsed (whole-set, fail-closed) by `sig::keys::parse_baked_keys`.
//! - [`REQUIRE_KEYS`] decouples "keys are MANDATORY" from "the `secure-boot`
//!   feature is compiled in" (FIX-24): a measure-only build (`tpm.measure` with
//!   no signing enforcement) compiles the `secure-boot` feature yet legitimately
//!   ships NO signing keys, so it must build with an empty set. Signature
//!   ENFORCEMENT builds set this `true`, and the Nix `assertMsg` plus the Rust
//!   zero-keys `const _` assert in `sig::keys` then make an empty set a hard
//!   error — never a silent runtime allow-all.
//!
//! The pinned per-key path scheme is `src/sig/baked_key_{N}.bin` (0-based), the
//! exact strings the regenerator emits and the fileset unions back in.

use super::alg::AlgId;

/// The baked public-key trust anchor: `(raw encoded public-key bytes, alg)`
/// pairs. Committed EMPTY; regenerated by `mkNmblInit { publicKeys }`. The raw
/// bytes are the EXACT pre-image `sig::wire::fp` fingerprints (FIX-65) and are
/// `alg.pk_len()` long for a well-formed key (enforced by the per-key `const _`
/// length assert in `sig::keys`).
pub(crate) static BAKED_KEYS: &[(&[u8], AlgId)] = &[];

/// Whether at least one baked key is MANDATORY for this build (FIX-24).
///
/// `false` in the committed stub and in measure-only builds. The signature
/// enforcement build (regenerated by Nix) sets this `true`, at which point an
/// empty [`BAKED_KEYS`] is a compile error (see `sig::keys`'s `const _` assert)
/// — fail-closed at build time, never an allow-all at runtime.
pub const REQUIRE_KEYS: bool = false;
