//! [`DetachedShell`] and [`spawn_shell_on_tty`]: fire-and-forget shell on a raw tty.

use std::ffi::CString;
use std::os::fd::{AsRawFd, OwnedFd};
use std::path::Path;

use nix::unistd::{ForkResult, fork, setsid};

use super::{EXEC_FAILED_EXIT_CODE, preflight_shell, prepare_shell_cstrings};
use crate::error::{NmblError, Result};
use crate::sys::ops::FsOps;

/// Handle to a fire-and-forget shell whose stdio is wired directly to
/// an operator-supplied tty (no PTY in the middle). Returned by
/// [`spawn_shell_on_tty`] so the orchestrator can wait on / reap the
/// child without holding a relay loop open.
///
/// The orchestrator drops back to the previous TUI screen immediately
/// after this returns; the shell runs to its natural conclusion on the
/// operator's chosen tty, completely independent of NMBL's event loop.
pub struct DetachedShell {
    /// Pid of the spawned child. Used for the boot-time reaper at PID 1
    /// to eventually collect; we intentionally do NOT `waitpid` in the
    /// fire-and-forget caller because that would block on a shell that
    /// could outlive the entire NMBL session.
    pub pid: nix::unistd::Pid,
}

/// Open the target tty in the parent so an `open(2)` failure surfaces
/// synchronously. The fd is inherited across `fork`; the child `dup2`s it
/// onto 0/1/2 before `execve`.
fn open_tty_fd(tty_path: &Path) -> Result<OwnedFd> {
    use rustix::fs::{Mode as RustixMode, OFlags as RustixOFlagsAlias};
    rustix::fs::open(
        tty_path,
        RustixOFlagsAlias::RDWR | RustixOFlagsAlias::NOCTTY,
        RustixMode::empty(),
    )
    .map_err(|e| NmblError::Tui {
        source: std::io::Error::other(format!(
            "opening shell tty {} failed: {e}",
            tty_path.display()
        )),
    })
}

/// Post-fork child path for `spawn_shell_on_tty`. Restricted to
/// async-signal-safe primitives. Wires `tty_raw` onto stdio and
/// `execve`s the shell.
///
/// # Safety
/// Must only be called from the child branch of `fork()`. No allocation,
/// no Rust I/O, no destructors. All `CString` args were allocated in the
/// parent before `fork`.
unsafe fn child_exec_on_tty(
    tty_raw: i32,
    path_c: &CString,
    argv0_c: &CString,
    env_term: &CString,
    env_path: &CString,
) -> ! {
    // Detach + own the tty as our controlling terminal. setsid
    // is async-signal-safe; failure means we'll just lack a
    // session — the shell still runs.
    let _ = setsid();
    // SAFETY: libc::ioctl is async-signal-safe; TIOCSCTTY=0
    // claims the tty as the controlling terminal for the new
    // session created by setsid above. Failure is non-fatal
    // (e.g. on a non-VT line) and the shell still runs.
    let _ = unsafe { libc::ioctl(tty_raw, libc::TIOCSCTTY as _, 0) };

    // Dup the tty onto 0/1/2 so the shell's stdio runs on the
    // operator's line.
    for target in [0, 1, 2] {
        if unsafe { libc::dup2(tty_raw, target) } < 0 {
            // SAFETY: post-fork child; _exit is the only correct
            // termination primitive. Same exception documented
            // in spawn_shell above.
            unsafe { libc::_exit(EXEC_FAILED_EXIT_CODE) };
        }
    }
    // Close the original tty fd if it wasn't 0/1/2.
    if tty_raw > 2 {
        // SAFETY: close on a valid fd; async-signal-safe.
        let _ = unsafe { libc::close(tty_raw) };
    }

    let argv: [*const libc::c_char; 2] = [argv0_c.as_ptr(), std::ptr::null()];
    let envp: [*const libc::c_char; 3] = [env_term.as_ptr(), env_path.as_ptr(), std::ptr::null()];

    // SAFETY: libc::execve is async-signal-safe. On success it
    // does not return.
    // execve safety: we are a forked child process, not PID 1; our job is to replace ourselves with the requested shell.
    let _ = unsafe { libc::execve(path_c.as_ptr(), argv.as_ptr(), envp.as_ptr()) };

    // SAFETY: Unavoidable. Post-fork child must use _exit (the
    // existing documented exception to the "no new unsafe" rule).
    unsafe { libc::_exit(EXEC_FAILED_EXIT_CODE) }
}

/// Fork a shell whose stdin/stdout/stderr are duplicated to `tty_path`
/// and return immediately. NO PTY allocation; the shell runs directly
/// on the operator-supplied char device. Used by the console-picker's
/// fire-and-forget path: when the operator selects targets that do
/// NOT include the splash's current display tty, NMBL must spawn the
/// shell on those targets and return to the previous screen, not enter
/// a relay loop on the wrong fd.
///
/// The shell becomes the session leader on `tty_path` so signals
/// generated by the keyboard (^C, ^Z) are routed correctly. The parent
/// (NMBL) keeps no fd into the line; reaping is left to the PID-1
/// init-style reaper that NMBL's main loop already runs.
pub fn spawn_shell_on_tty(
    fs: &dyn FsOps,
    shell_path: &Path,
    tty_path: &Path,
) -> Result<DetachedShell> {
    // Same preflight as spawn_shell: a missing /bin/sh would otherwise
    // produce a "Shell spawned" toast for a child that instantly
    // _exit(127)s, masking the real problem. The presence check routes
    // through the FsOps seam.
    preflight_shell(fs, shell_path)?;

    // === Parent-side allocation: ALL CString / Vec construction MUST
    // happen here, before fork(2). The post-fork child path is restricted
    // to async-signal-safe operations (same discipline as spawn_shell). ===
    let (path_c, argv0_c, env_term, env_path) = prepare_shell_cstrings(shell_path)?;

    // Open the target tty in the PARENT so an open(2) failure surfaces
    // synchronously (not as an opaque _exit code from a forked child).
    // The fd is then inherited across fork; the child dup2's it onto
    // 0/1/2 before execve.
    let tty_fd = open_tty_fd(tty_path)?;
    let tty_raw = tty_fd.as_raw_fd();

    // SAFETY: `nix::unistd::fork` is `unsafe` by design (no safe wrapper
    // exists). The child branch is restricted to async-signal-safe
    // primitives (`setsid`, `ioctl`, `dup2`, `close`, `execve`, `_exit`)
    // — no allocation, no Rust I/O, no destructors. All CString and
    // OwnedFd allocations are completed above in the parent.
    let fork_result = unsafe { fork() }.map_err(|e| NmblError::Tui {
        source: std::io::Error::other(format!("fork() for detached shell: {e}")),
    })?;

    match fork_result {
        ForkResult::Parent { child } => {
            // The child owns the tty fd through the dup2 chain; the
            // parent's copy is no longer needed. Dropping it here is
            // safe — the kernel reference-counts the open file.
            drop(tty_fd);
            Ok(DetachedShell { pid: child })
        }
        ForkResult::Child => {
            // === CHILD ===
            // Same async-signal-safe constraints as `spawn_shell`. We
            // must NOT panic, allocate, or run Rust destructors here.
            // SAFETY: we are in the child branch of fork(); child_exec_on_tty
            // is restricted to async-signal-safe calls and does not return.
            unsafe { child_exec_on_tty(tty_raw, &path_c, &argv0_c, &env_term, &env_path) }
        }
    }
}
